### PR TITLE
Increase Smartfridge capacity

### PR DESCRIPTION
**Pull request by Yatosamasensei**
## About The Pull Request
Increase Organ storage capacity to 50

## Why It's Good For The Game

So it doesn't get as full as easily

## Changelog
:cl:
tweak: Smart Organ Storage capacity increased to 50

/:cl:

### CODE REVIEW

**Comment by jaw-sh** [comment]
Why do you need 50 organs? And what does this mean:
`vastly lower to prevent processing too long`

Seems like they have that option in for a reason.

**Comment by Yatosamasensei** [comment]
I've on several occassions had it fill up. If i had to guess its so it doesn't take time to open like current research does. But that is a small price to pay to have more room

**Comment by jaw-sh** [comment]
Are you sure that's not to prevent some organ related ticks from happening too frequently?

**Comment by Yatosamasensei** [comment]
I really don't have any way to tell. I'll ask around TG see if anyone knows

**Comment by Yatosamasensei** [comment]
I haven't been able to find any information on this. and testing it wouldn't really have any effect since I can't test with the same server hardware as the server.

**Pull request closed without merging**
